### ISSUE TITLE
ignoreValues option does not work as expected

### ISSUE THREAD

**Issue by danny-andrews** [Mavrin/stylelint-declaration-use-css-custom-properties#3]
**STR**
.stylelintrc.yaml:

```yaml
plugins:
  - "@mavrin/stylelint-declaration-use-css-custom-properties"
rules:
  mavrin/stylelint-declaration-use-css-custom-properties:
    cssDefinitions: ["length"]
    ignoreValues: ["0"]
```
example.reset.css

```yaml
* {
  padding: 0;
  margin: 2rem;
  font-size: 20rem;
}
```

**Expected**
Lines three and four result in a lint error for a length value not declared as a css custom property

**Actual**
Only line three results in a lint error.

I believe this is because `20rem` contains an `0`.

I think the proper fix is to change [this line](https://github.com/Mavrin/stylelint-declaration-use-css-custom-properties/blob/master/index.js#L32) to `return value === name`. There's no need to do `.includes` here because if someone wants matching functionality, they should just use a regular expression, no?
